FROM trailofbits/polytracker:latest
LABEL org.opencontainers.image.authors="henrik.brodin@trailofbits.com, kelly.kaoudis@trailofbits.com"
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /polytracker/the_klondike
RUN apt-get update && \
    apt-get install -y git && \
    git clone https://github.com/uclouvain/openjpeg.git
ENV LLVM_SYMBOLIZER_PATH=llvm-symbolizer-12

# build release binary - noting that CMAKE_BUILD_TYPE Release, which roughly equals adding -O3 -DNDEBUG to the compiler options, is not compatible with the cflog instrumentation pass -DCMAKE_BUILD_TYPE=RelWithDebInfo
WORKDIR /polytracker/the_klondike/openjpeg/build/release
RUN polytracker build cmake -GNinja -S ../.. -B . \
    -DBUILD_JPWL:bool=ON \
    -DBUILD_MJ2:bool=ON \
    -DBUILD_DOC=OFF \
    -DBUILD_LUTS_GENERATOR=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DBUILD_UNIT_TESTS=OFF \
    -DBUILD_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_EXE_LINKER_FLAGS="-L/polytracker/the_klondike/openjpeg/build/release/bin -l:libopenjp2.a"
RUN polytracker build cmake --build . -j$(nproc)
RUN polytracker instrument-targets --taint --ftrace --cflog opj_decompress

# build debug binary
WORKDIR /polytracker/the_klondike/openjpeg/build/debug
RUN polytracker build cmake -GNinja -S ../.. -B . \
    -DBUILD_JPWL:bool=ON \
    -DBUILD_MJ2:bool=ON \
    -DBUILD_DOC=OFF \
    -DBUILD_LUTS_GENERATOR=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DBUILD_UNIT_TESTS=OFF \
    -DBUILD_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_EXE_LINKER_FLAGS="-L/polytracker/the_klondike/openjpeg/build/debug/bin -l:libopenjp2.a"
RUN polytracker build cmake --build . -j$(nproc)
RUN polytracker instrument-targets --taint --ftrace --cflog opj_decompress

# References:
# https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-3575
# https://github.com/uclouvain/openjpeg/issues/1347
# https://github.com/uclouvain/openjpeg/pull/1362
# The file shouldn't be decompressed if: either there is no EOC marker found, or Rsiz value is non compliant. Grok refuses to decompress the PoC in the open PR discussion, yet openjpeg attempts.

# WORKDIR /polytracker/the_klondike/openjpeg/

# RUN wget https://github.com/uclouvain/openjpeg/files/6402272/poc.j2k.gz && \
#     gunzip poc.j2k.gz

# # Test command: opj_decompress -i poc.j2k -o poc.j2k.png, using the appropriate binary we built above
# # This will create the TDAG and functionid.json traces for comparison.

WORKDIR /polytracker/the_klondike/openjpeg/
