line-length = 127
target-version = "py312"

exclude = [
  ".git",
  "__pycache__",
  "polytracker/src/compiler-rt/**",
  "examples/**",
  "the_klondike",
  "third_party",
]

[lint]
select = ["B", "D3", "D4", "E", "F", "W", "C9", "I", "UP"]
ignore = ["E501", "F403", "F405", "E265", "E203"]

[lint.mccabe]
max-complexity = 15
