FROM trailofbits/polytracker
MAINTAINER Carson Harmon <carson.harmon@trailofbits.com>

WORKDIR /polytracker/the_klondike

ENV CC=clang 
ENV CXX=clang++

#Set up sources list to auto get build-dep
RUN cp /etc/apt/sources.list /etc/apt/sources.list~
RUN sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list

#Update pkg-config/util-linux (needed for FontConfig)
RUN apt update
RUN apt install pkg-config uuid-dev gperf libtool \
	gettext autopoint autoconf -y

RUN apt-get build-dep libpoppler73 -y

#=================================
WORKDIR /polytracker/the_klondike

#FreeType http://www.linuxfromscratch.org/blfs/view/svn/general/freetype2.html
RUN wget https://downloads.sourceforge.net/freetype/freetype-2.10.1.tar.xz
RUN tar -xvf freetype-2.10.1.tar.xz

WORKDIR freetype-2.10.1 

#Some linux from scratch magic
RUN sed -ri "s:.*(AUX_MODULES.*valid):\1:" modules.cfg
RUN sed -r "s:.*(#.*SUBPIXEL_RENDERING) .*:\1:" \
    -i include/freetype/config/ftoption.h 
RUN ./configure --prefix=/usr --enable-freetype-config --disable-shared 
RUN make install

#=================================
WORKDIR /polytracker/the_klondike

#Fontconfig (depends on FreeType), note that the linux from scratch version is broken
#The gitlab version is up to date, and has a PR merged from a year ago with the bug fix
#https://gitlab.freedesktop.org/fontconfig/fontconfig/merge_requests/2/diffs?commit_id=8208f99fa1676c42bfd8d74de3e9dac5366c150c

RUN git clone https://gitlab.freedesktop.org/fontconfig/fontconfig.git
WORKDIR fontconfig
RUN ./autogen.sh --sysconfdir=/etc --prefix=/usr --mandir=/usr/share/man
RUN ./configure --prefix=/usr --disable-shared
RUN make install

#=================================
WORKDIR /polytracker/the_klondike

#Poppler 0.84.0

RUN wget https://poppler.freedesktop.org/poppler-0.84.0.tar.xz
RUN tar -xvf poppler-0.84.0.tar.xz
WORKDIR poppler-0.84.0
RUN mkdir build
WORKDIR build
RUN cmake -DBUILD_SHARED_LIBS=OFF -DENABLE_LIBOPENJPEG=unmaintained -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang ..

#=================================
WORKDIR /polytracker/the_klondike

# Note, the /workdir directory is intended to be mounted at runtime
VOLUME ["/workdir"]
WORKDIR /workdir
