FROM ubuntu:focal
LABEL org.opencontainers.image.authors="kelly.kaoudis@trailofbits.com"
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /

# We use dependency versions that are noted as compliant with the
# unix imagemagick build instructions:
# https://github.com/ImageMagick/ImageMagick/blob/7.1.0-23/Install-unix.txt
# https://www.imagemagick.org/script/advanced-linux-installation.php
# We instrument with asan and ubsan following https://clang.llvm.org/docs/AddressSanitizer.html#usage (dynamic linking required, etc)

RUN apt-get update && \
  apt-get install -y \
    autoconf \
    autopoint \
    clang-12 \
    cmake \
    gettext \
    git \
    golang \
    liblzma-dev \
    libtool \
    libxml2-dev \
    python3-dev \
    unzip \
    wget && \
  # imagemagick #
  wget https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.0-23.tar.gz && \
  tar xvf 7.1.0-23.tar.gz && \
  mv ImageMagick-7.1.0-23 imagemagick && \
  # zlib #
  wget https://zlib.net/fossils/zlib-1.3.tar.gz && \
  tar xvf zlib-1.3.tar.gz && \
  mv zlib-1.3 /imagemagick/zlib && \
  # libjpeg (v9e) #
  wget https://ijg.org/files/jpegsrc.v9e.tar.gz && \
  tar xvf jpegsrc.v9e.tar.gz && \
  mv jpeg-9e /imagemagick/libjpeg && \
  # libpng #
  wget https://downloads.sourceforge.net/libpng/libpng-1.6.39.tar.xz && \
  tar xvf libpng-1.6.39.tar.xz && \
  mv libpng-1.6.39 /imagemagick/libpng && \
  # libtiff #
  wget https://download.osgeo.org/libtiff/tiff-4.3.0.tar.gz && \
  tar xvf tiff-4.3.0.tar.gz && \
  mv tiff-4.3.0 /imagemagick/libtiff

# Install symlinks to clang and llvm bitcode tools
RUN update-alternatives --install /usr/bin/opt opt /usr/bin/opt-12 10 && \
    update-alternatives --install /usr/bin/llvm-link llvm-link /usr/bin/llvm-link-12 10 && \
    update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-12 10 && \
    update-alternatives --install /usr/bin/llvm-symbolizer llvm-symbolizer /usr/bin/llvm-symbolizer-12 10 && \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 10 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 10 && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3 10

ENV ASAN_SYMBOLIZER_PATH=/usr/bin/llvm-symbolizer

# build debug version of zlib
WORKDIR /imagemagick/zlib
RUN \
  CFLAGS="-O0 -g -fno-omit-frame-pointer" \
  CPPFLAGS="-O0 -g -fno-omit-frame-pointer" \
  CC=clang \
  CXX=clang++ \
  ./configure && \
  make -j$((`nproc`+1))

# build debug version of libjpeg
WORKDIR /imagemagick/libjpeg
RUN \
  AR_FLAGS="crs" \
  CFLAGS="-O0 -g -fno-omit-frame-pointer" \
  CC=clang \
  ./configure \
    --enable-shared \
    --disable-static \
    --prefix="/imagemagick/libjpeg" \
    --exec-prefix="/imagemagick/libjpeg" && \
    make -j$((`nproc`+1)) && \
    make install

# build debug version of libpng linking our built zlib
WORKDIR /imagemagick/libpng
RUN cp scripts/makefile.linux Makefile
RUN \
  CFLAGS="-O0 -g -fno-omit-frame-pointer" \
  CPPFLAGS="-I/imagemagick/zlib/include -O0 -g -fno-omit-frame-pointer" \
  LDFLAGS="-L/imagemagick/zlib" \
  CC=clang \
  make -j$((`nproc`+1))

# build debug version of libtiff linking our built archives
WORKDIR /imagemagick/libtiff
RUN \
  DIR_GZLIB="/imagemagick/zlib" \
  DIR_JPEGLIB="/imagemagick/libjpeg" \
  DIRS_LIBINC="/imagemagick/zlib /imagemagick/libjpeg" \
  CC=clang \
  CXX=clang++ \
  CPPFLAGS="-I/imagemagick/zlib -I/imagemagick/libjpeg/include"\
  CFLAGS="-O0 -g -fno-omit-frame-pointer" \
  CXXFLAGS="-O0 -g -fno-omit-frame-pointer" \
  LDFLAGS="-L/imagemagick/zlib -L/imagemagick/libjpeg/lib -lpthread" \
  ./configure \
    --enable-shared \
    --disable-static \
    --prefix="/imagemagick/libtiff" \
    --exec-prefix="/imagemagick/libtiff" && \
  make -j$((`nproc`+1)) && \
  make install

# build debug version of imagemagick
WORKDIR /imagemagick
RUN ./configure \
    --disable-static \
    --enable-shared \
    --without-magick-plus-plus \
    --without-x \
    --disable-silent-rules \
    --without-lcms \
    --without-perl \
    --disable-installed \
    --with-frozenpaths \
    --prefix="/imagemagick" \
    PKG_CONFIG="" \
    LD_LIBRARY_PATH="/imagemagick/zlib:/imagemagick/libjpeg/lib:/imagemagick/libpng:/imagemagick/libtiff/lib:$LD_LIBRARY_PATH" \
    LDFLAGS="-L/imagemagick/zlib -L/imagemagick/libjpeg/lib -L/imagemagick/libpng -L/imagemagick/libtiff/lib -fPIC" \
    CC=clang \
    CXX=clang++ \
    CFLAGS="-fsanitize=address,undefined -O0 -g -fno-omit-frame-pointer" \
    CPPFLAGS="-fsanitize=address,undefined -O0 -g -fno-omit-frame-pointer" \
    LIBS="-lz -lpng -ljpeg -ltiff -lgomp -lxml2 -llzma -lstdc++" && \
  make -j$((`nproc`+1))