#!/bin/bash

set -eu -o pipefail

# Find the directory containing this bash script.
# See https://stackoverflow.com/questions/59895/get-the-source-directory-of-a-bash-script-from-within-the-script-itself.
#
# We do this so that we can assume that the test process will be running from
# within the test directory.
#
# This scheme will need to be refined if eventually we want to support any
# command-line arguments for our test driver.
TEST_DIR=$(dirname "$(readlink -f "$0")")
cd "$TEST_DIR"

python3.7 -mvenv .venv
source .venv/bin/activate
pip install -qq pytest
exec python3.7 -mpytest -v
